### ISSUE TITLE
Fatal error: Allowed memory size exhausted

### ISSUE THREAD

**Issue by jor3l** [fdeschenes/cakephp-dompdf-view#2]
Hello there, 

Was checking out the plugin and got this error, not sure what is wrong, any idea?

Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 64 bytes) in /PATH/lib/Cake/View/View.php on line 995

Thank you!

**Comment by jor3l** [comment]
Well, using controller/.pdf worked, but controller/index.pdf gives another Fatal error ;)

**Comment by fdeschenes** [comment]
Thanks for reporting this. I'll have a look and see if I can find the cause.  It should work with the action name in the URL.  What version of CakePHP are you using?

**Comment by jor3l** [comment]
Sorry for the late response, cakephp 2.3.1.
